const places=[
{id:'ajanta',name:'Ajanta Caves',state:'Maharashtra',period:'Ancient',forms:['Painting','Sculpture','Architecture','Religious'],region:'West',years:'2nd century BCE – 5th century CE',x:42,y:58,img:'https://commons.wikimedia.org/wiki/Special:FilePath/Ajanta%20Caves%2C%20India%2C%20Buddha%20statue%20and%20paintings.jpg',text:'Ajanta is one of the great surviving traditions of ancient Indian mural painting. Its rock-cut caves preserve Buddhist narratives, sculpture and architecture created across several centuries.',high:['Famous for exquisite Buddhist murals','Jataka tales, court life, nature and spiritual themes','Notable Bodhisattva Padmapani and Vajrapani imagery','Natural pigments and fresco-secco painting traditions']},
{id:'ellora',name:'Ellora Caves',state:'Maharashtra',period:'Medieval',forms:['Sculpture','Architecture','Religious'],region:'West',years:'6th – 10th century CE',x:44,y:55,img:'https://commons.wikimedia.org/wiki/Special:FilePath/Kailasa%20Temple%2C%20Ellora%2C%20India.jpg',text:'Ellora brings Buddhist, Hindu and Jain traditions together in a monumental complex of rock-cut architecture and sculpture, including the extraordinary Kailasa temple.',high:['Three major religious traditions share one landscape','Monumental rock-cut architecture','Kailasa temple is carved from a single rock mass','UNESCO World Heritage Site']},
{id:'kutch',name:'Kutch',state:'Gujarat',period:'Modern',forms:['Textile','Folk'],region:'West',years:'Living tradition',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Rogan%20art.jpg',x:18,y:49,text:'Kutch is a vibrant centre for textile, embroidery, weaving and painting traditions. Its craft practices carry community knowledge through generations.',high:['Embroidery and textile arts','Rogan painting tradition','Distinct community-based visual languages','Living craft heritage']},
{id:'jaipur',name:'Jaipur',state:'Rajasthan',period:'Early Modern',forms:['Painting','Architecture'],region:'North',years:'16th – 19th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/City%20Palace%20Jaipur%20India.jpg',x:28,y:37,text:'Jaipur developed as a major centre of Rajput court culture, architecture, manuscript painting, decorative arts and later the refined visual traditions associated with Rajasthan.',high:['Rajput court patronage','Miniature painting traditions','Palace and architectural arts','Manuscript illustration']},
{id:'kangra',name:'Kangra',state:'Himachal Pradesh',period:'Early Modern',forms:['Painting','Religious'],region:'North',years:'18th – 19th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Kangra%20painting.jpg',x:34,y:21,text:'Kangra became a celebrated centre of Pahari miniature painting, especially lyrical depictions of Krishna, Radha, poetry, music and landscapes.',high:['Pahari miniature tradition','Krishna and Radha themes','Lyrical landscapes and expressive line','Courtly patronage']},
{id:'sanchi',name:'Sanchi',state:'Madhya Pradesh',period:'Ancient',forms:['Sculpture','Architecture','Religious'],region:'Central',years:'3rd century BCE onward',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Sanchi%20Stupa%20No.%201.jpg',x:46,y:43,text:'Sanchi preserves some of the most important early Buddhist monuments in India, including stupas and richly carved gateways depicting stories, symbols and sacred imagery.',high:['Early Buddhist architecture','Narrative relief sculpture','Stupa and torana traditions','Major archaeological heritage site']},
{id:'khajuraho',name:'Khajuraho',state:'Madhya Pradesh',period:'Medieval',forms:['Sculpture','Architecture','Religious'],region:'Central',years:'10th – 12th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Kandariya%20Mahadeva%20Temple%20Khajuraho.jpg',x:56,y:41,text:'Khajuraho is renowned for the sculptural richness of its temple complexes. Gods, musicians, dancers, mythical beings and scenes of everyday life animate the architecture.',high:['Chandela-period temple art','Highly developed stone sculpture','Sacred and worldly imagery','UNESCO World Heritage Site']},
{id:'madhubani',name:'Madhubani',state:'Bihar',period:'Modern',forms:['Painting','Folk'],region:'East',years:'Living tradition',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Madhubani%20painting.jpg',x:65,y:30,text:'Mithila or Madhubani painting is a living regional tradition known for strong outlines, filled surfaces, symbolic motifs and stories drawn from mythology and community life.',high:['Mithila painting tradition','Natural and synthetic pigments','Geometric and symbolic compositions','Women artists played a major historic role']},
{id:'kolkata',name:'Kolkata & Santiniketan',state:'West Bengal',period:'Modern',forms:['Painting','Architecture'],region:'East',years:'19th – 20th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Abanindranath%20Tagore%20-%20Bharat%20Mata.jpg',x:70,y:47,text:'Bengal became a major centre of modern Indian art. The Bengal School, Abanindranath Tagore, Rabindranath Tagore and Santiniketan reshaped ideas of Indian modernism.',high:['Bengal School of Art','Abanindranath Tagore','Rabindranath Tagore and Santiniketan','Dialogue between Indian and global modernism']},
{id:'majuli',name:'Majuli',state:'Assam',period:'Medieval',forms:['Sculpture','Folk','Religious'],region:'Northeast',years:'15th century CE onward',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Majuli%20mask%20making.jpg',x:89,y:32,text:'Majuli is closely associated with the Vaishnavite sattra culture of Assam, where performance, mask-making, music and religious storytelling form a connected artistic world.',high:['Sattra cultural tradition','Handmade masks','Performance and storytelling','Living ritual arts']},
{id:'raghurajpur',name:'Raghurajpur',state:'Odisha',period:'Medieval',forms:['Painting','Folk','Religious'],region:'East',years:'Living tradition',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Pattachitra%20painting.jpg',x:68,y:56,text:'Raghurajpur is a renowned heritage crafts village associated with Pattachitra, a disciplined painting tradition built around mythological narratives and strong decorative design.',high:['Pattachitra painting','Jagannath-related visual culture','Palm-leaf and painted craft traditions','Village-based artist communities']},
{id:'hampi',name:'Hampi',state:'Karnataka',period:'Medieval',forms:['Sculpture','Architecture','Religious'],region:'South',years:'14th – 16th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Vittala%20Temple%20Hampi.jpg',x:45,y:68,text:'Hampi was the monumental heart of the Vijayanagara Empire. Its temples, sculpture, markets and civic spaces reveal a powerful synthesis of religion, court culture and architecture.',high:['Vijayanagara architecture','Temple sculpture and reliefs','Monumental urban landscape','UNESCO World Heritage Site']},
{id:'sri',name:'Srikalahasti',state:'Andhra Pradesh',period:'Medieval',forms:['Painting','Textile','Religious'],region:'South',years:'Living tradition',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Kalamkari%20painting.jpg',x:55,y:71,text:'Srikalahasti is an important centre for Kalamkari, a hand-painted textile tradition using narrative imagery, natural dyes and a painstaking drawing process.',high:['Kalamkari textile painting','Natural dye processes','Epic and temple narratives','Hand-drawn visual storytelling']},
{id:'thanjavur',name:'Thanjavur',state:'Tamil Nadu',period:'Early Modern',forms:['Painting','Sculpture','Religious'],region:'South',years:'16th – 19th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Tanjore%20painting.jpg',x:50,y:84,text:'Thanjavur became known for an opulent devotional painting tradition marked by rich colour, relief work, gold foil and jewel-like embellishment.',high:['Tanjore painting','Gold-leaf and relief ornament','Devotional iconography','Maratha-period court influence']},
{id:'maha',name:'Mahabalipuram',state:'Tamil Nadu',period:'Ancient',forms:['Sculpture','Architecture','Religious'],region:'South',years:'7th – 8th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Shore%20Temple%20Mahabalipuram.jpg',x:59,y:80,text:'Mahabalipuram preserves the celebrated stone architecture and sculpture of the Pallavas, including rathas, cave temples and monumental reliefs.',high:['Pallava stone architecture','Rathas and cave temples','Monumental relief sculpture','UNESCO World Heritage Site']},
{id:'kerala',name:'Kerala',state:'Kerala',period:'Medieval',forms:['Painting','Architecture','Religious'],region:'South',years:'9th century CE onward',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Kerala%20mural%20painting.jpg',x:37,y:86,text:'Kerala’s temple mural tradition uses mineral and plant-derived pigments, stylised figures and narrative compositions to cover sacred architectural spaces.',high:['Temple mural painting','Mythological narratives','Distinctive stylised figures','Ritual and architectural context']},
{id:'delhi',name:'Delhi',state:'Delhi',period:'Colonial',forms:['Architecture','Painting'],region:'North',years:'19th – 20th century CE',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Humayuns%20Tomb%20Delhi.jpg',x:39,y:32,text:'Delhi sits at the intersection of several historical art traditions, from Sultanate and Mughal architecture to colonial institutions and the modern cultural infrastructure of independent India.',high:['Mughal architectural heritage','Colonial-era institutions','Modern galleries and museums','Layered urban history']},
{id:'varanasi',name:'Varanasi',state:'Uttar Pradesh',period:'Medieval',forms:['Painting','Textile','Religious'],region:'North',years:'Ancient – present',img:'https://commons.wikimedia.org/wiki/Special:FilePath/Varanasi%20ghats.jpg',x:53,y:34,text:'Varanasi has long been a major centre of sacred arts and crafts, with painting, silk weaving, music, ritual objects and architectural heritage intertwined with the city’s religious life.',high:['Banarasi textile traditions','Sacred painting and objects','Temple and riverfront architecture','Living cultural landscape']}
];

const periods=['All','Ancient','Medieval','Early Modern','Colonial','Modern','Contemporary'];
const forms=['All','Painting','Sculpture','Architecture','Textile','Folk','Tribal','Religious'];
const regions=['All','North','South','East','West','Central','Northeast'];
let filters={period:'All',form:'All',region:'All'};
let current=places[0];

function makeChips(id,arr,key){document.getElementById(id).innerHTML=arr.map(v=>`<button class="chip ${filters[key]===v?'active':''}" data-key="${key}" data-value="${v}">${v}</button>`).join('')}
function renderFilters(){makeChips('periods',periods,'period');makeChips('forms',forms,'form');makeChips('regions',regions,'region');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{filters[b.dataset.key]=b.dataset.value;renderFilters();render()})}
function visible(p){return (filters.period==='All'||p.period===filters.period)&&(filters.form==='All'||p.forms.includes(filters.form))&&(filters.region==='All'||p.region===filters.region)}
function render(){const m=document.getElementById('markers');m.innerHTML='';const list=places.filter(visible);list.forEach(p=>{const el=document.createElement('div');el.className='marker '+(p.id===current.id?'selected':'');el.style.left=p.x+'%';el.style.top=p.y+'%';el.innerHTML=`<div class="pin"></div><div class="marker-label">${p.name}</div>`;el.onclick=()=>openDetail(p);m.appendChild(el)});document.getElementById('count').textContent=`${list.length} location${list.length===1?'':'s'}`;renderCards(list)}
function openDetail(p){current=p;document.getElementById('detailTitle').textContent=p.name;document.getElementById('detailMeta').textContent=`${p.state}  ·  ${p.years}`;document.getElementById('detailImg').src=p.img;document.getElementById('detailImg').alt=p.name;document.getElementById('detailPills').innerHTML=[...p.forms,p.period].map(x=>`<span class="pill">${x}</span>`).join('');document.getElementById('detailText').textContent=p.text;document.getElementById('detailHighlights').innerHTML=p.high.map(x=>`<li>${x}</li>`).join('');document.getElementById('detail').scrollIntoView({behavior:'smooth',block:'nearest'});render()}
function renderCards(list){const chosen=[...list].sort((a,b)=>['ajanta','khajuraho','madhubani','thanjavur','hampi','kolkata'].indexOf(a.id)-['ajanta','khajuraho','madhubani','thanjavur','hampi','kolkata'].indexOf(b.id)).slice(0,6);document.getElementById('cards').innerHTML=chosen.map(p=>`<article class="card" data-id="${p.id}"><img src="${p.img}" alt="${p.name}" loading="lazy"><h3>${p.name}</h3><p>${p.state}</p></article>`).join('');document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openDetail(places.find(p=>p.id===c.dataset.id)))}

document.getElementById('reset').onclick=()=>{filters={period:'All',form:'All',region:'All'};renderFilters();render()};
document.getElementById('close').onclick=()=>{};
document.getElementById('galleryBtn').onclick=()=>alert('Gallery mode is ready for expansion — each location can hold multiple artwork images.');
document.getElementById('learnBtn').onclick=()=>document.getElementById('detail').scrollIntoView({behavior:'smooth',block:'center'});
document.getElementById('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase().trim();if(!q){render();return}const hits=places.filter(p=>`${p.name} ${p.state} ${p.text} ${p.forms.join(' ')} ${p.period}`.toLowerCase().includes(q));document.getElementById('count').textContent=`${hits.length} result${hits.length===1?'':'s'}`;document.getElementById('markers').innerHTML='';hits.forEach(p=>{const el=document.createElement('div');el.className='marker';el.style.left=p.x+'%';el.style.top=p.y+'%';el.innerHTML=`<div class="pin"></div><div class="marker-label">${p.name}</div>`;el.onclick=()=>openDetail(p);document.getElementById('markers').appendChild(el)})});
let scale=1;document.getElementById('zoomIn').onclick=()=>{scale=Math.min(1.35,scale+.1);document.querySelector('.map-canvas').style.transform=`scale(${scale})`};document.getElementById('zoomOut').onclick=()=>{scale=Math.max(.85,scale-.1);document.querySelector('.map-canvas').style.transform=`scale(${scale})`};
renderFilters();openDetail(places[0]);
